import { describe, expect, it } from "vitest";
// biome-ignore lint/performance/noNamespaceImport: verifies the complete public entry point
import * as contracts from "./index.ts";

const publicContractNames = [
  "agentIdSchema",
  "agentResponseSchema",
  "agentSchema",
  "agentStatusSchema",
  "agentVersionSchema",
  "agentVersionsResponseSchema",
  "agentsResponseSchema",
  "apiKeyTokenSchema",
  "approveMcpOauthAuthorizationBodySchema",
  "artifactDownloadUrlResponseSchema",
  "artifactListItemSchema",
  "artifactsListResponseSchema",
  "attributionCreateInputSchema",
  "blazingAgentsChatMessageMetadataSchema",
  "chatModeSchema",
  "chatRequestBodySchema",
  "chatTriggerSchema",
  "copySkillBodySchema",
  "createAgentBodySchema",
  "createMcpConnectionBodySchema",
  "createMemoryBodySchema",
  "createPromptBodySchema",
  "createProviderBodySchema",
  "createSkillBodySchema",
  "createTaskBodySchema",
  "createTaskResponseSchema",
  "createTaskRunBodySchema",
  "createTaskRunResponseSchema",
  "createWorkspaceBodySchema",
  "decideToolApprovalBodySchema",
  "generationRequestBodySchema",
  "isAdminAgentId",
  "jsonSchemaShapeSchema",
  "mcpAttachmentResponseSchema",
  "mcpAttachmentsResponseSchema",
  "mcpConnectionAuthTypeSchema",
  "mcpConnectionOauthConnectResponseSchema",
  "mcpConnectionReconnectResultSchema",
  "mcpConnectionResponseSchema",
  "mcpConnectionStatusSchema",
  "mcpConnectionTestErrorCodeSchema",
  "mcpConnectionTestResponseSchema",
  "mcpConnectionsResponseSchema",
  "mcpOauthAuthorizationLaunchResponseSchema",
  "memoriesListResponseSchema",
  "memoryResponseSchema",
  "memorySchema",
  "metadataSchema",
  "promptIdSchema",
  "promptResponseSchema",
  "promptSchema",
  "promptVariablesSchema",
  "promptsResponseSchema",
  "providerModelsResponseSchema",
  "providerResponseSchema",
  "providerTypeSchema",
  "providersResponseSchema",
  "quotaSchema",
  "receivedApiErrorResponseSchema",
  "reconnectMcpConnectionBodySchema",
  "sessionIdSchema",
  "sessionListItemSchema",
  "sessionMessageSchema",
  "sessionMessagesResponseSchema",
  "sessionsListResponseSchema",
  "skillCopyResultsSchema",
  "skillDetailSchema",
  "skillsListResponseSchema",
  "subscriptionStatusSchema",
  "taskListItemSchema",
  "taskResponseSchema",
  "taskRunMessagesResponseSchema",
  "taskRunResponseSchema",
  "taskRunSchema",
  "taskRunStatusSchema",
  "taskRunsListResponseSchema",
  "taskScheduleKindSchema",
  "taskSchema",
  "tasksListResponseSchema",
  "tenantResponseSchema",
  "tenantSchema",
  "tenantSettingsResponseSchema",
  "thinkingLevelsResponseSchema",
  "toolApprovalContinuationStateSchema",
  "toolApprovalDecisionResponseSchema",
  "toolApprovalStateSchema",
  "toolApprovalsResponseSchema",
  "updateAgentBodySchema",
  "updateMcpAttachmentBodySchema",
  "updateMcpConnectionBodySchema",
  "updateMemoryBodySchema",
  "updatePromptBodySchema",
  "updateProviderBodySchema",
  "updateTaskBodySchema",
  "updateTenantSettingsBodySchema",
  "updateWorkspaceBodySchema",
  "usageResponseSchema",
  "usageSummarySchema",
  "workspaceSchema",
  "workspacesListResponseSchema",
] as const;

describe("public contracts", () => {
  it("exports the explicit runtime schema surface", () => {
    expect(Object.keys(contracts).sort()).toEqual(publicContractNames);
  });

  it("validates public resource ids", () => {
    expect(contracts.agentIdSchema.parse("ag_0123456789abcdef")).toBe(
      "ag_0123456789abcdef"
    );
    expect(() => contracts.agentIdSchema.parse("agent_1")).toThrow();
    expect(contracts.promptIdSchema.parse("prompt_0123456789abcdef")).toBe(
      "prompt_0123456789abcdef"
    );
    expect(contracts.isAdminAgentId("ag_adm0123456789ABC")).toBe(true);
  });
});
